name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8 app.py test_app.py
      - name: Run unit tests
        run: |
          pytest test_app.py
      # - name: Deploy (optional)
      #   run: echo "Deploy step here (e.g., Streamlit Cloud, SSH, etc.)" 